name: Deploy to Github Pages
on:
    push:
        branches: [master]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
                  lfs: true

            - name: Download latest zig
              uses: goto-bus-stop/setup-zig@v1
              with:
                  version: master

            - uses: nektro/actions-setup-zigmod
              with:
                access-token: ${{ secrets.ACCESS_TOKEN }}

            - name: Fetch dependencies
              run: zigmod ci

            - name: Build for web target
              run: zig build web -Drelease-fast

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: zig-out/bin
